/* tslint:disable */
/* eslint-disable */
/**
 * HR Recruiter API
 * Полная OpenAPI спецификация для платформы автоматизации. Включает все основные сущности, бизнес-операции, заглушки для AI и медиа, а также примеры для быстрой интеграции.  **Аутентификация только через JWT (Bearer). Basic Auth не поддерживается.** 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
export * from "./models";
